#!/usr/bin/env python3
"""Build publication-ready summary tables from concordance analysis outputs."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path("/orcd/home/002/yuexing/NeuRIPS25/Figures/heatmap/_analysis_outputs")


def stars(p: float) -> str:
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    return "ns"


def fmt_ci(lo: float, hi: float) -> str:
    return f"[{lo:.2f}, {hi:.2f}]"


def df_to_markdown(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    body = []
    for _, row in df.iterrows():
        vals = []
        for c in cols:
            v = row[c]
            if isinstance(v, float):
                vals.append(f"{v:.4f}".rstrip("0").rstrip("."))
            else:
                vals.append(str(v))
        body.append("| " + " | ".join(vals) + " |")
    return "\n".join([header, sep] + body)


def main() -> None:
    model = pd.read_csv(ROOT / "model_level_summary.csv")
    pair = pd.read_csv(ROOT / "pairwise_jaccard_summary.csv")
    human = pd.read_csv(ROOT / "human_alignment_pairwise_tests_holm.csv")

    # Table 1: model ranking
    t1 = model.copy()
    t1 = t1.rename(
        columns={
            "model": "Model",
            "avg_pairwise_jaccard_to_others_pct": "Avg Jaccard vs Others (%)",
            "jaccard_with_human_pct": "Jaccard vs Human (%)",
        }
    )
    t1.insert(0, "Rank", range(1, len(t1) + 1))
    t1.to_csv(ROOT / "publication_table_model_ranking.csv", index=False)

    # Table 2: top/bottom pairwise concordance
    top_n = 10
    top = pair.head(top_n).copy()
    bottom = pair.tail(top_n).copy()
    top["Section"] = "Top 10"
    bottom["Section"] = "Bottom 10"
    t2 = pd.concat([top, bottom], ignore_index=True)
    t2 = t2.rename(
        columns={
            "model_a": "Model A",
            "model_b": "Model B",
            "n_origins_used": "N Origins",
            "mean_jaccard_pct": "Mean Jaccard (%)",
            "sd_jaccard_pct": "SD (%)",
        }
    )
    t2["95% CI"] = [
        fmt_ci(lo, hi) for lo, hi in zip(t2["ci95_low_jaccard_pct"], t2["ci95_high_jaccard_pct"])
    ]
    t2 = t2[["Section", "Model A", "Model B", "N Origins", "Mean Jaccard (%)", "SD (%)", "95% CI"]]
    t2.to_csv(ROOT / "publication_table_pairs_top_bottom.csv", index=False)

    # Table 3: strongest human-alignment differences
    t3 = human.copy()
    t3["p-value"] = t3["p_value_paired_t"]
    t3["Sig"] = t3["p-value"].map(stars)
    t3["Holm 0.05"] = t3["significant_holm_0p05"].map({True: "Yes", False: "No"})
    t3["95% CI of Delta"] = [
        fmt_ci(lo, hi) for lo, hi in zip(t3["ci95_low_diff_pct"], t3["ci95_high_diff_pct"])
    ]
    t3 = t3.rename(
        columns={
            "model_better_on_human": "Better Model (vs Human)",
            "model_worse_on_human": "Worse Model (vs Human)",
            "mean_diff_jaccard_with_human_pct": "Delta Jaccard vs Human (%)",
            "n_origins_used": "N Origins",
        }
    )
    t3 = t3[
        [
            "Better Model (vs Human)",
            "Worse Model (vs Human)",
            "Delta Jaccard vs Human (%)",
            "95% CI of Delta",
            "N Origins",
            "p-value",
            "Sig",
            "Holm 0.05",
        ]
    ]
    t3.to_csv(ROOT / "publication_table_human_alignment_tests.csv", index=False)

    # Markdown summary
    md = []
    md.append("# Concordance Summary Tables")
    md.append("")
    md.append("## Table 1. Model Ranking")
    md.append(df_to_markdown(t1.round(2)))
    md.append("")
    md.append("## Table 2. Top/Bottom Pairwise Concordance")
    md.append(df_to_markdown(t2.round(2)))
    md.append("")
    md.append("## Table 3. Human-Alignment Pairwise Tests (sorted by p-value)")
    t3_show = t3.head(20).copy()
    t3_show["Delta Jaccard vs Human (%)"] = t3_show["Delta Jaccard vs Human (%)"].map(lambda x: f"{x:.2f}")
    t3_show["p-value"] = t3_show["p-value"].map(lambda x: f"{x:.2e}")
    md.append(df_to_markdown(t3_show))
    md.append("")
    md.append("Significance stars: `*** p<0.001`, `** p<0.01`, `* p<0.05`, `ns` otherwise.")
    (ROOT / "publication_tables.md").write_text("\n".join(md))

    # Lightweight LaTeX tables
    latex_parts = []
    latex_parts.append("% Auto-generated by make_publication_summary_tables.py")
    latex_parts.append("% Table 1: Model ranking")
    latex_parts.append(t1.round(2).to_latex(index=False, escape=True))
    latex_parts.append("% Table 2: Top/bottom pairwise concordance")
    latex_parts.append(t2.round(2).to_latex(index=False, escape=True))
    latex_parts.append("% Table 3: Human-alignment tests (top 20)")
    latex_parts.append(t3_show.to_latex(index=False, escape=True))
    (ROOT / "publication_tables.tex").write_text("\n\n".join(latex_parts))

    print(f"Wrote {ROOT / 'publication_table_model_ranking.csv'}")
    print(f"Wrote {ROOT / 'publication_table_pairs_top_bottom.csv'}")
    print(f"Wrote {ROOT / 'publication_table_human_alignment_tests.csv'}")
    print(f"Wrote {ROOT / 'publication_tables.md'}")
    print(f"Wrote {ROOT / 'publication_tables.tex'}")


if __name__ == "__main__":
    main()
